AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template provisioning CodePipeline

Parameters:
  S3Bucket:
    Description: S3 Bucket containing deployment content
    Type: String
    Default: hmckenzie-web

  DeploymentFile:
    Description: Filename of the deployment
    Type: String
    Default: SampleApp_Linux.zip

Resources:
  Application:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: WebApp
      ComputePlatform: Server

  
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref Application
      AutoScalingGroups: 
        - Fn::ImportValue:
            ASG-WebASG
      Deployment:
        Description: Web server deployment
        Revision:
          RevisionType: S3
          S3Location:
            Bucket: !Sub ${S3Bucket}
            Key: !Sub ${DeploymentFile}
            BundleType: Zip
      DeploymentGroupName: Web-ASG
      ServiceRoleArn:
        Fn::ImportValue:
          IAM-CodeDeployRole