AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for hmckenzie.net compute infrastructure
Parameters:
  NetworkStackName:
    Description: Name of the CloudFormation network stack
    Type: String
    Default: hmckenzie-network
Resources:
  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: 'web-alb'
      Type: application
      SecurityGroups: 
      - Fn::ImportValue:
          SG-ELBWebAccess
      Subnets:
      - Fn::ImportValue:
          VPC-PublicSubnetA
      - Fn::ImportValue:
          VPC-PublicSubnetB
      - Fn::ImportValue:
          VPC-PublicSubnetC
  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ELB
      DefaultActions:
        - Type: forward