AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for hmckenzie.net compute infrastructure

Parameters:
  NetworkStackName:
    Description: Name of the CloudFormation network stack
    Type: String
    Default: hmckenzie-network
  SSLCertificate:
    Description: Arn of the SSL Certificate used on the internet facing ALB
    Type: String

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'Web-ALB'
      Type: application
      SecurityGroups: 
      - Fn::ImportValue:
          SG-ELBWebAccess
      Subnets:
      - Fn::ImportValue:
          VPC-PublicSubnetA
      - Fn::ImportValue:
          VPC-PublicSubnetB
      - Fn::ImportValue:
          VPC-PublicSubnetC

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref ALBTargetGroup
      Port: 80
      Protocol: HTTP

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref ALBTargetGroup
      Port: 443
      Protocol: HTTPS
      SslPolicy: "ELBSecurityPolicy-2016-08"
      Certificates:
        - CertificateArn: !Ref SSLCertificate

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      Name: web-tg
      Port: 80
      Protocol: HTTP
      VpcId: 
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPC