AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for hmckenzie.net compute infrastructure

Parameters:
  NetworkStackName:
    Description: Name of the CloudFormation network stack
    Type: String
    Default: hmckenzie-network
  SSLCertificate:
    Description: Arn of the SSL Certificate used on the internet facing ALB
    Type: String

Resources:
  # Load Balancer Configuration
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'Web-ALB'
      Type: application
      SecurityGroups: 
      - Fn::ImportValue:
          SG-ELBWebAccess
      Subnets:
      - Fn::ImportValue:
          VPC-PublicSubnetA
      - Fn::ImportValue:
          VPC-PublicSubnetB
      - Fn::ImportValue:
          VPC-PublicSubnetC

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Port: 80
      Protocol: HTTP

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref ALBTargetGroup
      Port: 443
      Protocol: HTTPS
      SslPolicy: "ELBSecurityPolicy-2016-08"
      Certificates:
        - CertificateArn: !Ref SSLCertificate

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      Name: web-tg
      Port: 80
      Protocol: HTTP
      VpcId: 
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPC

  # EC2 and Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Web-ASG
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      VPCZoneIdentifier:
        - VPC-PublicSubnetA
        - VPC-PublicSubnetB
        - VPC-PublicSubnetC

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      LaunchConfigurationName: Web-LaunchConfiguration
      ImageId: ami-04c2a5c7e6c051fb2
      InstanceType: t4g.micro
      KeyName: hmckenzie-ireland
      SecurityGroups:
        - Fn::ImportValue:
            SG-EC2ELBAccess